development:
  bin: rsync
  opts: "-lptzv --delete -e ssh"
  dest_path: zomeki@192.168.0.0:/var/www/zomeki/

test:
  bin: rsync
  opts: "-lptzv --delete -e ssh"
  dest_path: zomeki@192.168.0.0:/var/www/zomeki/

production:
  bin: rsync
  opts: "-lptzv --delete -e ssh"
  dest_path: zomeki@192.168.0.0:/var/www/zomeki/
